name: 'kubectl command line tool for github actions'
description: Kubectl command for github action
author: 'Abhijith V <abhijithababhijith@gmail.com>'
branding:
  icon: 'terminal'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'